backend:
  name: git-gateway
  branch: main # The branch to update (optional; defaults to master)
  publish_mode: editorial_workflow


media_folder: "src/blog/img" # Media files will be stored in the repo under images/uploads

collections:
  # Our blog posts
  - name: "posts" # Used in routes, e.g., /admin/collections/blog
    label: "Posty" # Used in the UI
    folder: "src/blog" # The path to the folder where the documents are stored
    media_folder: "img/"
    public_folder: "/blog/img/"
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Tytuł", name: "title", widget: "string" }
      - { label: "Obrazek", name: "postThumb", widget: "image" }
      - { label: "Data", name: "date", widget: "datetime" }
      - { label: "Autor", name: "author", widget: "string", default: "Psotel Gracja" }
      - { label: "Body", name: "body", widget: "markdown" }


  # Faq
  - label: "FAQ"
    name: faq
    folder: "src/faq"
    create: true
    fields: 
      - name: Pytanie i odpowiedź
        label: Pytanie i odpowiedź
        widget: list
        fields:
          - {label: "Pytanie", name: "pytanie", widget: "string"}
          - {label: "Odpowiedź", name: "odpowiedz", widget: "text"}

